/control/echo === RUNNING: run.mac ===

/control/verbose 0
/tracking/verbose 0
/event/verbose 0
/gps/verbose 0

/run/initialize

/gps/particle mu-
/gps/pos/type Plane
/gps/pos/shape Circle
#/gps/pos/shape Square
/gps/pos/centre 0 0 1 m
#/gps/pos/radius 1 cm
/gps/pos/radius 3.65 cm
#/gps/pos/halfx 3.65 cm
#/gps/pos/halfy 3.65 cm
/gps/direction 0 0 -1

/gps/number 1
/gps/ene/type Lin
/gps/ene/min 10 MeV
/gps/ene/max 100 MeV
/gps/ene/gradient 0
/gps/ene/intercept 1

/run/printProgress 10000
/run/beamOn 100000

